### ISSUE TITLE
Try all 16 possible combinations of input sheets

### ISSUE THREAD

**Issue by trixr4kdz** [kdahlquist/GRNmap#74]
Combined with the 3 test cases from @bengfitzpatrick, make dummy cases of excel sheets with different combinations (e.g fix b, est p, graph, or fix b, fix p, no graph, etc.)

**Comment by kdahlquist** [comment]
To provide a little more detail on this, the options include:
* Sigmoidal vs. Michaelis-Menten
* forward only vs. estimation + forward
* FixP vs. estimated P
* Fixb vs. estimated b (Sigmoidal only)
* makeGraphs vs. don't makeGraphs

We want to document what we want to happen for each of the combinations and what actually happens, in case we uncover any bugs.  I.e., did the correct form of the model run, did it do forward only or did it perform the estimation, did the requested parameters get estimated, did the graphs get made and saved.

At our next meeting, we will determine which worksheets should appear in the output workbook for each of the 16 possible runs.

**Comment by trixr4kdz** [comment]
I was checking through the test inputs in http://www.openwetware.org/wiki/GRNmap_Test_Inputs and found that Input 12 and Input 14 have incorrect parameters. I put makeGraphs = 1 in Input 12, but it really should be = 0. Also, in Input 14 fix_P = 1 when it should be = 0.

**Comment by trixr4kdz** [comment]
I fixed the incorrect inputs I reported above in http://www.openwetware.org/wiki/GRNmap_Test_Inputs and uploaded the output sheets

**Comment by dondi** [comment]
For some side viewing, here is a video of “Uncle Bob” Martin, one of the prominent advocators of test-driven development, demonstrating the process live in Santa Monica last week:

https://www.youtube.com/watch?v=D9GQ9nBHhIc&feature=youtu.be&list=PL06ytJZ4Ak1quT7gKXcNKD3lj

**Comment by kdahlquist** [comment]
Almost done with analyzing data from these runs. @kdahlquist will sit down with @trixr4kdz  and @tessaam to review results.

**Comment by tessaam** [comment]
I am now making the smaller sets so they can be used for testing.

**Comment by tessaam** [comment]
I created the 16 different input sheets and with the help of Trixie uploaded them onto the beta version of GRNmap. 
I created two new folders in the "test_files" subfolder called "sixteen_tests" and "sixteen_tests_output" where the "sixteen_tests" contains the input sheets and the "sixteen_tests_output" contains the output sheet.

http://openwetware.org/wiki/GRNmap_Testing_Report_16_Test_Files_2015-06-01#Updating_GRNmap_on_Github

**Comment by tessaam** [comment]
The newest version of GRNmap (4:40 pm 2015-06-01) needs the sheet to be (strain)_log2_expression rather than just (strain). The current sheet names in the "sixteen_tests" file still has the sheet named (strain). I can update the input sheets, but should I run them all again and get new output sheets?

**Comment by bengfitzpatrick** [comment]
@tessaam let's wait till the matlab code functionality is added before changing the sheet names.

**Comment by bengfitzpatrick** [comment]
@tessaam since you are dealing with the test files, there is a data bug I'd like you to check.  In some of the test files, there are times listed as 0.4, 0.8, 1.2, and 1.6 in one sheet and 0.4, 0.8, 1.2, and 1.4 in another sheet.  Can you check the times for consistency? 1.6 is the correct data. I am not sure which test files are involved.

**Comment by tessaam** [comment]
In the subfolders "estimation_tests" and "forward_tests" the workbook, "4-genes_6-edges_artificial-data_Sigmoid_estimation.xls" was the only sheet with the time inconsistency. I changed the time in the optimization parameters sheet to match the log2_expression data (0.4, 0.8, 1.2, and 1.6) and saved it as a new file ("4-genes_6-edges_artificial-data_Sigmoid_estimation_updated.xlsx") and ran it. The output file is saved in the same folder ("estimation_tests"), named "4-genes_6-edges_artificial-data_Sigmoid_estimation_updated_output.xlsx"

Because this was the sheet that was used as the base for each of the 16 files in "sixteen_tests" I will correct this in all 16 sheets and run them again.

**Comment by bengfitzpatrick** [comment]
thanks @tessaam

**Comment by tessaam** [comment]
The functions that produce the sheets optimized_production_rates  and optimized_threshold_b are working correctly. When fixP-0 the optimized_production_rates sheet was produced; fixP-1 no production rates sheet was produced. When fixb-0 the optimized_threshold_b sheet was produced; fixb-1 no optimized_threshold_b sheet was produced. 
The wt_log2_optimized_expression, wt_sigmas, dcin5_log2_optimized_expression, and dcin5_sigmas sheets were produced for all of the inputs. 
The optimization_diagnostics sheet was not produced for any of the inputs. 

http://openwetware.org/wiki/GRNmap_Testing_Report_16_Test_Files_2015-06-01#Checking_production_rates.2C_threshold_b.2C_and_Output_file_names

**Comment by kdahlquist** [comment]
@tessaam needs to update the "large" files 22-genes_47-edges to be compliant with new sheet names.  when this is done, can close the issue.

**Comment by tessaam** [comment]
Input sheets are corrected, but not all of the corrected output sheets have been created and uploaded to the wiki. 
http://openwetware.org/wiki/GRNmap_Testing_Report_16_Test_Files_from_Dahlquist-data_2015-05-26_TM

**Comment by kdahlquist** [comment]
run tests on beta and when beta is verified it will be merged to master so no further tests need to be done on master.

**Comment by tessaam** [comment]
I ran all 16 combinations with alpha = 0.001. MaxIter = 1.00E+06, TolFun = 1.00E-05,  MaxFunEval = 1.00E+06, and TolX =1.00E-05.

I found the following issues: 
* When makegraph = 0 MATLAB does not save the optimization_diagnostic jpg. 
* When estimateparms = 0  there is no .mat file output and MATLAB shows the error: 
   Error in output (line 140)
   outputDiag{3,2} = GRNstruct.GRNOutput.reg_out;
   Error in GRNmodel (line 34)
   GRNstruct = output(GRNstruct); 

http://openwetware.org/wiki/GRNmap_Testing_Report_16_Test_Files_from_Dahlquist-data_2015-05-26_TM

**Comment by kdahlquist** [comment]
@tessaam reported some bugs in this issue that she discovered when running all 16 test files.  @tessaam , would you please verify that these bugs still exist and then create separate issues for them?  When you report the issue, be specific as to which branch of the code you used and which specific test file causes the bug.

Once you have broken these bugs out as separate issues, we will close this one.  I think I'm correct in that everything else discussed in this issue is done, right?

**Comment by kdahlquist** [comment]
As this is now broken out into two issues #132 and #133, we are going to close this one.
